# Generated by Django 4.0.4 on 2022-05-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='title_tag',
            field=models.CharField(default='SDU BLOG', max_length=1000),
        ),
    ]
